name: Publish

# Triggers the workflow on tags that are "v*.*.*"
on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [latest]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm ci
      - id: release
        run: |
          npm run release
          echo "::set-output name=ffxpi::$(ls dist/ad_blocker_for_facebook_*.zip)"

      # Publish to Chrome
      - name: Chrome Addon Action
        uses: trmcnvn/chrome-addon@v2
        continue-on-error: true
        with:
          extension: kinpgphmiekapnpbmobneleaiemkefag
          zip: dist/chrome.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      # Publish to Firefox
      - name: Firefox Addon Action
        uses: trmcnvn/firefox-addon@v1
        continue-on-error: true
        with:
          uuid: "{d403ee9c-3bd2-41d3-b1e9-27698babf097}"
          xpi: ${{ steps.release.outputs.ffxpi }}
          manifest: dist/src/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
